### ISSUE TITLE
Help - accessing rejected pull requests

### ISSUE THREAD

**Issue by rhfogh** [mxcube/ui-api#8]
Pull request #7 has a lot of interesting discussion we should keep, but it would be easier to reject it and submit a new one, rather than to merge it and then totally change it by a new pull request. 

Is there a way to keep the discussion without accepting the PR?

Rasmus

**Comment by marcus-oscarsson** [comment]
Hi Rasmus,

Just make your changes and push it again :), it will be updated automatically 

Marcus
